# Docker Compose para desarrollo local
version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8003:8000"
    volumes:
      - ./models:/app/models
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

  # Si quieres agregar una base de datos más adelante
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: eventweather
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data: