version: "3.9"

services:
  backend:
    build: .
    ports:
      - "8004:8000"
    volumes:
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://eventweather_user:eventweather_pass@postgres:5432/eventweather_db
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: eventweather_db
      POSTGRES_USER: eventweather_user
      POSTGRES_PASSWORD: eventweather_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@eventweather.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
